# ❗❗❗ 초기 실행이거나 볼륨을 삭제하셨다면 컨테이너 실행 후 ❗❗❗
# ❗❗❗ 꼭 `./init-replication.sh` 스크립트 파일을 실행해주세요. ❗❗❗
services:
  mysql-master:
    container_name: couponpop-mysql-master
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_MASTER_PORT}:3306'
    volumes:
      - db-master:/var/lib/mysql
      - db-master:/var/lib/mysql-files
    command:
      - --innodb-buffer-pool-size=128M
      - --max-connections=50
      - --default_authentication_plugin=mysql_native_password
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --max-binlog-size=100M
      - --expire-logs-days=7
      - --sync-binlog=1
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
    networks:
      - mysql-net

  mysql-slave:
    container_name: couponpop-mysql-slave
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_SLAVE_PORT}:3306'
    volumes:
      - db-slave:/var/lib/mysql
      - db-slave:/var/lib/mysql-files
    command:
      - --innodb-buffer-pool-size=128M
      - --max-connections=50
      - --default-authentication-plugin=mysql_native_password
      - --server-id=2
      - --relay-log=mysql-relay-bin
      - --binlog-format=ROW
      - --read-only=1
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
    networks:
      - mysql-net

volumes:
  db-master:
  db-slave:

networks:
  mysql-net:
    driver: bridge
